// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelState = `-- name: GetChannelState :one
SELECT channel_id, item_position, item_started_at, status, last_error, updated_at FROM channel_state WHERE channel_id = $1
`

func (q *Queries) GetChannelState(ctx context.Context, channelID int32) (ChannelState, error) {
	row := q.db.QueryRow(ctx, getChannelState, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.ItemPosition,
		&i.ItemStartedAt,
		&i.Status,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunningChannelStates = `-- name: ListRunningChannelStates :many
SELECT channel_id, item_position, item_started_at, status, last_error, updated_at FROM channel_state WHERE status = 'running'
`

func (q *Queries) ListRunningChannelStates(ctx context.Context) ([]ChannelState, error) {
	rows, err := q.db.Query(ctx, listRunningChannelStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelState
	for rows.Next() {
		var i ChannelState
		if err := rows.Scan(
			&i.ChannelID,
			&i.ItemPosition,
			&i.ItemStartedAt,
			&i.Status,
			&i.LastError,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelState = `-- name: UpsertChannelState :one
INSERT INTO channel_state (channel_id, item_position, item_started_at, status, last_error, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (channel_id) DO UPDATE
SET item_position = EXCLUDED.item_position, item_started_at = EXCLUDED.item_started_at,
    status = EXCLUDED.status, last_error = EXCLUDED.last_error, updated_at = now()
RETURNING channel_id, item_position, item_started_at, status, last_error, updated_at
`

type UpsertChannelStateParams struct {
	ChannelID     int32
	ItemPosition  int32
	ItemStartedAt pgtype.Timestamptz
	Status        string
	LastError     pgtype.Text
}

func (q *Queries) UpsertChannelState(ctx context.Context, arg UpsertChannelStateParams) (ChannelState, error) {
	row := q.db.QueryRow(ctx, upsertChannelState,
		arg.ChannelID,
		arg.ItemPosition,
		arg.ItemStartedAt,
		arg.Status,
		arg.LastError,
	)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.ItemPosition,
		&i.ItemStartedAt,
		&i.Status,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}
