// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, number, slug, video_width, video_height, video_bitrate_k)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, number, slug, enabled, video_width, video_height, video_bitrate_k, created_at, deleted_at
`

type CreateChannelParams struct {
	Name          string
	Number        int32
	Slug          string
	VideoWidth    int32
	VideoHeight   int32
	VideoBitrateK int32
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Number,
		arg.Slug,
		arg.VideoWidth,
		arg.VideoHeight,
		arg.VideoBitrateK,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Slug,
		&i.Enabled,
		&i.VideoWidth,
		&i.VideoHeight,
		&i.VideoBitrateK,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, number, slug, enabled, video_width, video_height, video_bitrate_k, created_at, deleted_at FROM channels WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetChannel(ctx context.Context, id int32) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Slug,
		&i.Enabled,
		&i.VideoWidth,
		&i.VideoHeight,
		&i.VideoBitrateK,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelBySlug = `-- name: GetChannelBySlug :one
SELECT id, name, number, slug, enabled, video_width, video_height, video_bitrate_k, created_at, deleted_at FROM channels WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetChannelBySlug(ctx context.Context, slug string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelBySlug, slug)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Slug,
		&i.Enabled,
		&i.VideoWidth,
		&i.VideoHeight,
		&i.VideoBitrateK,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, number, slug, enabled, video_width, video_height, video_bitrate_k, created_at, deleted_at FROM channels WHERE deleted_at IS NULL ORDER BY number
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Number,
			&i.Slug,
			&i.Enabled,
			&i.VideoWidth,
			&i.VideoHeight,
			&i.VideoBitrateK,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChannel = `-- name: SoftDeleteChannel :exec
UPDATE channels SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteChannel(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteChannel, id)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $2, number = $3, slug = $4, enabled = $5,
    video_width = $6, video_height = $7, video_bitrate_k = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, number, slug, enabled, video_width, video_height, video_bitrate_k, created_at, deleted_at
`

type UpdateChannelParams struct {
	ID            int32
	Name          string
	Number        int32
	Slug          string
	Enabled       bool
	VideoWidth    int32
	VideoHeight   int32
	VideoBitrateK int32
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Number,
		arg.Slug,
		arg.Enabled,
		arg.VideoWidth,
		arg.VideoHeight,
		arg.VideoBitrateK,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.Slug,
		&i.Enabled,
		&i.VideoWidth,
		&i.VideoHeight,
		&i.VideoBitrateK,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
