// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_events.sql

package sqlc

import (
	"context"
)

const insertChannelEvent = `-- name: InsertChannelEvent :exec
INSERT INTO channel_events (channel_id, level, message) VALUES ($1, $2, $3)
`

type InsertChannelEventParams struct {
	ChannelID int32
	Level     string
	Message   string
}

func (q *Queries) InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error {
	_, err := q.db.Exec(ctx, insertChannelEvent, arg.ChannelID, arg.Level, arg.Message)
	return err
}

const listChannelEvents = `-- name: ListChannelEvents :many
SELECT id, channel_id, level, message, created_at FROM channel_events WHERE channel_id = $1 ORDER BY id DESC LIMIT $2
`

type ListChannelEventsParams struct {
	ChannelID int32
	Limit     int32
}

func (q *Queries) ListChannelEvents(ctx context.Context, arg ListChannelEventsParams) ([]ChannelEvent, error) {
	rows, err := q.db.Query(ctx, listChannelEvents, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelEvent
	for rows.Next() {
		var i ChannelEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
