// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMediaFile = `-- name: GetMediaFile :one
SELECT id, path, size, mtime, duration_ms, video_codec, probe, probed_at FROM media_files WHERE path = $1
`

func (q *Queries) GetMediaFile(ctx context.Context, path string) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFile, path)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Size,
		&i.Mtime,
		&i.DurationMs,
		&i.VideoCodec,
		&i.Probe,
		&i.ProbedAt,
	)
	return i, err
}

const getMediaFilesByPaths = `-- name: GetMediaFilesByPaths :many
SELECT id, path, size, mtime, duration_ms, video_codec, probe, probed_at FROM media_files WHERE path = ANY($1::text[])
`

func (q *Queries) GetMediaFilesByPaths(ctx context.Context, paths []string) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, getMediaFilesByPaths, paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Size,
			&i.Mtime,
			&i.DurationMs,
			&i.VideoCodec,
			&i.Probe,
			&i.ProbedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMediaFile = `-- name: UpsertMediaFile :one
INSERT INTO media_files (path, size, mtime, duration_ms, video_codec, probe, probed_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (path) DO UPDATE
SET size = EXCLUDED.size, mtime = EXCLUDED.mtime, duration_ms = EXCLUDED.duration_ms,
    video_codec = EXCLUDED.video_codec, probe = EXCLUDED.probe, probed_at = now()
RETURNING id, path, size, mtime, duration_ms, video_codec, probe, probed_at
`

type UpsertMediaFileParams struct {
	Path       string
	Size       int64
	Mtime      pgtype.Timestamptz
	DurationMs int64
	VideoCodec string
	Probe      []byte
}

func (q *Queries) UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, upsertMediaFile,
		arg.Path,
		arg.Size,
		arg.Mtime,
		arg.DurationMs,
		arg.VideoCodec,
		arg.Probe,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Size,
		&i.Mtime,
		&i.DurationMs,
		&i.VideoCodec,
		&i.Probe,
		&i.ProbedAt,
	)
	return i, err
}
