// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID            int32
	Name          string
	Number        int32
	Slug          string
	Enabled       bool
	VideoWidth    int32
	VideoHeight   int32
	VideoBitrateK int32
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	SourceFolder  pgtype.Text
}

type ChannelEvent struct {
	ID        int32
	ChannelID int32
	Level     string
	Message   string
	CreatedAt pgtype.Timestamptz
}

type ChannelState struct {
	ChannelID     int32
	ItemPosition  int32
	ItemStartedAt pgtype.Timestamptz
	Status        string
	LastError     pgtype.Text
	UpdatedAt     pgtype.Timestamptz
}

type MediaFile struct {
	ID         int32
	Path       string
	Size       int64
	Mtime      pgtype.Timestamptz
	DurationMs int64
	VideoCodec string
	Probe      []byte
	ProbedAt   pgtype.Timestamptz
}

type PlaylistItem struct {
	ID        int32
	ChannelID int32
	Position  int32
	Path      string
	CreatedAt pgtype.Timestamptz
}
