// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist_items.sql

package sqlc

import (
	"context"
)

const deletePlaylistItems = `-- name: DeletePlaylistItems :exec
DELETE FROM playlist_items WHERE channel_id = $1
`

func (q *Queries) DeletePlaylistItems(ctx context.Context, channelID int32) error {
	_, err := q.db.Exec(ctx, deletePlaylistItems, channelID)
	return err
}

const insertPlaylistItems = `-- name: InsertPlaylistItems :many
INSERT INTO playlist_items (channel_id, position, path)
SELECT $1, unnest($2::int[]), unnest($3::text[])
RETURNING id, channel_id, position, path, created_at
`

type InsertPlaylistItemsParams struct {
	ChannelID int32
	Positions []int32
	Paths     []string
}

func (q *Queries) InsertPlaylistItems(ctx context.Context, arg InsertPlaylistItemsParams) ([]PlaylistItem, error) {
	rows, err := q.db.Query(ctx, insertPlaylistItems, arg.ChannelID, arg.Positions, arg.Paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistItem
	for rows.Next() {
		var i PlaylistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Position,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistItems = `-- name: ListPlaylistItems :many
SELECT id, channel_id, position, path, created_at FROM playlist_items WHERE channel_id = $1 ORDER BY position
`

func (q *Queries) ListPlaylistItems(ctx context.Context, channelID int32) ([]PlaylistItem, error) {
	rows, err := q.db.Query(ctx, listPlaylistItems, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistItem
	for rows.Next() {
		var i PlaylistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Position,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
